[project]
name = "voz-tts-ptbr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pedro Victor Veras", email = "pedrovictor.rveras12@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "kokoro>=0.9.4",
    "numpy>=2.5.2",
    "sounddevice>=0.5.5",
    "soundfile>=0.14.0",
]

[project.scripts]
voz-tts-ptbr = "voz_tts_ptbr:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
